# Generated by Django 5.0.6 on 2024-06-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_sale',
            field=models.BooleanField(default=False),
        ),
    ]
