# Generated by Django 5.0.6 on 2024-06-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productdetail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('yellow', 'yellow')], max_length=50),
        ),
    ]
