# Generated by Django 5.0.6 on 2024-06-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productdetail_image_alter_productdetail_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='productdetail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_detail', to='store.productdetail'),
        ),
    ]
