# Generated by Django 5.0.6 on 2024-06-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_receipt_productdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electric', 'Electric'), ('Food', 'Food'), ('Clothes', 'Clothes')], max_length=20),
        ),
    ]
